<?php

/**
 * @file
 * Main module file.
 */


/**
 * Implements hook_form_alter().
 */
function cd_applenews_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, "_node_form")) {
    if ($form['applenews']) {
      $form['applenews']['publish_flag']['#default_value'] = TRUE;
      if (isset($form['applenews']['channels']['section-2efb6837-9082-4cfe-9209-cc69ad5bc77a-5031edc8-92c4-4d9b-8b69-dc94a7ae6727'])) {
        $form['applenews']['channels']['section-2efb6837-9082-4cfe-9209-cc69ad5bc77a-5031edc8-92c4-4d9b-8b69-dc94a7ae6727']['#default_value'] = TRUE;
      }
    }
  }
}

/**
 * Implements hook_applenews_api().
 */
function cd_applenews_applenews_api() {
  return [
    'api' => 1,
    'exports' => [
      'node' => [
        'class' => 'ApplenewsCommonDreamsExportNode',
        'name' => t('Nodes'),
        'description' => t('Custom Apple News styled node export.'),
        'default' => 'cd_applenews_applenews_api_export_default_node',
      ],
    ],
    'destinations' => [
      'body' => [
        'class' => 'ApplenewsCommonDreamsDestinationBody',
        'name' => 'CD Body',
      ],
    ],
  ];
}

/**
 * Callback to define default node export.
 */
function cd_applenews_applenews_api_export_default_node(ApplenewsCommonDreamsExportNode $export) {

  // Apply to articles if exists.
  $entities_info = entity_get_info('node');
  if (isset($entities_info['bundles']['article'])) {
    $export->bundles = ['article'];
  }

  // Metadata.
  /** @var ApplenewsDestinationMetadata $metadata */
  $metadata = applenews_new_destination('applenews', 'metadata');
  $metadata
    ->setSetting('date_published', [
      'source' => '::::applenews::node::created',
      'value' => '',
      'bundle' => TRUE,
    ])
    ->setSetting('date_created', [
      'source' => '::::applenews::node::created',
      'value' => '',
      'bundle' => TRUE,
    ])
    ->setSetting('date_modified', [
      'source' => '::::applenews::node::changed',
      'value' => '',
      'bundle' => TRUE,
    ]);
  $export->setMetadata($metadata);

  // Header.
  /** @var ApplenewsDestinationText $component */
  $component = applenews_new_destination('cd_applenews', 'header_image');
  $component->weight = '0';
  $component->title = 'Header Image';
  $component
    ->setSetting('file', [
      'source' => '::::applenews::file::node::field_image::uri',
      'value' => '',
      'bundle' => TRUE,
    ]);
  $export->addComponent($component);

  // Title/Credits.
  /** @var ApplenewsCommonDreamsDestinationHeaderGradContainer $component */
  $component = applenews_new_destination('cd_applenews', 'header_container');
  $component->weight = '1';
  $component->title = 'Title/Credits';
  $component
    ->setSetting('title', [
      'source' => '::::applenews::node::label',
      'value' => '',
      'bundle' => TRUE,
    ])
    ->setSetting('author', [
      'source' => '::::applenews::node::author::::applenews::user::label',
      'value' => '',
      'bundle' => TRUE,
    ]);
  $export->addComponent($component);

  // Ad.
  /** @var ApplenewsCommonDreamsDestinationAd $component */
  $component = applenews_new_destination('cd_applenews', 'ad');
  $component->weight = '2';
  $component->title = 'Ad';
  $export->addComponent($component);

  // Body.
  /** @var ApplenewsCommonDreamsDestinationBody $component */
  $component = applenews_new_destination('cd_applenews', 'body');
  $component->weight = '3';
  $component->title = 'Body';
  $component
    ->setSetting('text', [
      'source' => '::::applenews::field::node::body::value_sanitized',
      'value' => '',
      'bundle' => TRUE,
    ])
    ->setSetting('format', 'markdown');
  $export->addComponent($component);

  // Pull Quote.
  /** @var ApplenewsCommonDreamsDestinationPullQuote $component */
  $component = applenews_new_destination('cd_applenews', 'pullquote');
  $component->weight = '4';
  $component->title = 'Pull Quote';
  $export->addComponent($component);

  // Gallery.
  /** @var ApplenewsCommonDreamsDestinationImages $component */
  $component = applenews_new_destination('cd_applenews', 'images');
  $component->weight = '5';
  $component->title = 'Gallery';
  $export->addComponent($component);
  $component
    ->setSetting('type', 'gallery');

}
