# settings
- upgrade_action_settings
- upgrade_d7_action
- upgrade_d7_advagg_settings
- upgrade_d7_dblog_settings
- upgrade_d7_file_private
- upgrade_d7_filter_settings
- upgrade_d7_global_theme_settings
- upgrade_d7_image_settings
- upgrade_d7_image_styles
- upgrade_d7_language_negotiation_settings
- upgrade_d7_language_types
- upgrade_d7_pathauto_settings
- upgrade_d7_robotstxt_settings
- upgrade_d7_search_page
- upgrade_d7_search_settings
- upgrade_d7_system_authorize
- upgrade_d7_system_cron
- upgrade_d7_system_date
- upgrade_d7_system_mail
- upgrade_d7_system_performance
- upgrade_d7_theme_settings
- upgrade_system_image
- upgrade_system_image_gd
- upgrade_system_logging
- upgrade_system_maintenance
- upgrade_system_rss
- upgrade_system_site
- upgrade_taxonomy_settings
- upgrade_text_settings
- upgrade_update_settings
- upgrade_d7_filter_format
- upgrade_default_language