name = Common Dreams
description = A custom 3 column layout for Common Dreams.
preview = preview.png
template = cdreams-layout

; Regions
regions[over_branding]       = Over Branding
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/cdreams/cdreams.layout.css
stylesheets[all][] = ../../css/omega-dreams.normalize.css
stylesheets[all][] = ../../css/omega-dreams.hacks.css
stylesheets[all][] = ../../css/omega-dreams.styles.css
stylesheets[all][] = ../../css/omega-dreams.no-query.css
stylesheets[all][] = ../../css/editor.css
