name = Bootstrap
description = Bootstrap based layout.
preview = preview.png
template = bootstrap-layout

; Regions
regions[header]         = Header
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/bootstrap.min.css
stylesheets[all][] = css/custom.css

; Javascript
scripts[] = js/bootstrap.bundle.min.js

