# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysqldb:
    type: mysql:10.2
    disk: 6144
    configuration:
        schemas:
            - main
            - legacy
        endpoints:
            admin:
                default_schema: main
                privileges:
                    main: admin
                    legacy: admin
            importer:
                default_schema: legacy
                privileges:
                    legacy: admin

rediscache:
    type: redis:5.0
